### PR TITLE
Complete example for latest substrate release

### PR DESCRIPTION
**Pull request by mmagician**
Building on previous review PRs from @apopiak, @j16r & with help from @LaurentTrk - see his other [PR](https://github.com/smartcontractkit/chainlink-polkadot/pull/39)

### CODE REVIEW

**Comment by boxhock** [comment]
Hi @mmagician, thanks a lot for creating this PR!

I'm trying to run through everything here and make sure that it works, but I'm having some issues compiling it.

When running `make run-chain` in the root directory, I get a bunch of errors related to this:
```
error: array lengths can't depend on generic parameters
   --> /home/jonashals/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/sgemm_kernel.rs:223:40
    |
223 |     let mut ab = [_mm256_setzero_ps(); MR];
    |                                        ^^
```

If I try running the `docker_run.sh` script, I get a few errors related to this:
```
  error[E0282]: type annotations needed
      --> /var/www/node-template/.cargo/git/checkouts/substrate-7e08433d4c370a21/be8bb18/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Are there any versions here that are outdated, that needs to be updated?

I also see this is using version 2.0.0-rc6 -- has a final version been released here we can use instead of rc?

**Comment by mmagician** [comment]
@boxhock I haven't tried it with the official release yet, and my feeling is that the errors you're seeing are related to using a newer Rust nightly with an old rc6. I'll try to have a look in the next couple of days

**Comment by LaurentTrk** [comment]
Hi @boxhock @mmagician 
The work is almost finished on my side for the substrate 2.0.0 official release.
I will make a new PR this weekend, including the PR from Marcin (https://github.com/smartcontractkit/chainlink-polkadot/pull/40) and mine (https://github.com/smartcontractkit/chainlink-polkadot/pull/39).

**Comment by mmagician** [comment]
Superseded by https://github.com/smartcontractkit/chainlink-polkadot/pull/42

**Pull request closed without merging**
